# -*- coding: utf-8 -*-
"""알고리즘 팀플 - 순차탐색 응용 예시.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15j4g0MIYLn1Grhl_c4KrSlzmDWTe7fnH

- 데이터베이스 검색
"""

# 데이터베이스 검색
# 특정 레코드를 찾을 때 사용될 수 있다.
# 예를 들어, 주어진 조건에 맞는 사용자를 찾을 때 사용된다.

def sequential_search(database, target_user):
    for user in database:
        if user == target_user:
            return True
    return False

# 출력 예시

database = ["A", "B", "C", "D"]
# True
target_user = "C"

# False
# target_user = "E"

result = sequential_search(database, target_user)
print(result)  # 출력: True

"""- 리스트나 배열에서 원소 찾기"""

# 리스트나 배열에서의 원소 찾기
# 리스트나 배열에서 특정 값을 찾을 때 순차 탐색 사용

def sequential_search_list(arr, target):
    for i, element in enumerate(arr):
        if element == target:
            return i  # 인덱스 반환
    return -1  # 찾지 못한 경우

# 출력 예시

arr = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]

target = 9
result_index = sequential_search_list(arr, target)
print(result_index)  # 출력: 5 (인덱스)

target = 7
result_index = sequential_search_list(arr, target)
print(result_index)  # 출력: -1 (찾지 못함)

"""- 파일 시스템 탐색"""

# 파일 시스템 탐색
# 파일 시스템에서 특정 파일이나 디렉토리를 찾을 때 순차 탐색 적용

import os

def sequential_search_file(directory, target_file):
    for root, dirs, files in os.walk(directory):
        if target_file in files:
            return os.path.join(root, target_file)  # 파일의 전체 경로 반환
    return None  # 찾지 못한 경우

# 출력 예시

directory = '/path/to/search'
target_file = 'example.txt'

result_path = sequential_search_file(directory, target_file)
print(result_path)  # 출력: '/path/to/search/example.txt' (파일의 전체 경로)

target_file = 'nonexistent.txt'
result_path = sequential_search_file(directory, target_file)
print(result_path)  # 출력: None (찾지 못함)

"""- 문장에서 특정 문자가 몇 번 나오는지 세는 함수"""

def count_char_occurrences(sentence, target_char):
    count = 0
    for char in sentence:       # 주어진 문자열'sentence'를 순회하며 각 문자 확인
        if char == target_char:
            count += 1          # 현재 문자가 찾고자 하는 문자'target_char'와 같다면 'count' 증가
    return count

# 출력 예시

sentence = "Hello, World!"
target_char = "l"

result = count_char_occurrences(sentence, target_char)
print(result)  # 출력: 3